services:
  echo-graalvm-distroless:
    build:
      context: .
      dockerfile: Dockerfile_graalvm_distroless
    container_name: echo-graalvm-distroless
    volumes:
      - ./resources/config.edn:/app/resources/config.edn

  echo-graalvm:
    build:
      context: .
      dockerfile: Dockerfile_graalvm
    container_name: echo-graalvm
    restart: always
    volumes:
      - ./resources/config.edn:/app/resources/config.edn

  echo-jvm:
    build:
      context: .
      dockerfile: Dockerfile_jvm
    container_name: echo-jvm
    restart: always
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
