services:
  echo-graalvm:
    image: ghcr.io/macielti/echo-graalvm:sha-2da2c33-linux-amd64
    container_name: echo-graalvm
    restart: always
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    deploy:
      resources:
        limits:
          memory: "25MB"
