services:
  echo-graalvm:
    image: ghcr.io/macielti/beagle-graalvm:sha-466676d
    container_name: echo-graalvm
    restart: always
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    deploy:
      resources:
        limits:
          memory: "25MB"
